lexik_jwt_authentication:
    secret_key:  '%kernel.project_dir%/config/jwt/private.pem'
    public_key:  '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '12321'
    token_ttl:    86400
